# This file is used to build and deploy the app into a GKE cluster using Google
# Cloud Build.
#
# Requirements:
# - Give the Google Cloud Build service account "Kubernetes Engine Developer"
#   IAM role on the GCP project.
# - Set up Google Cloud Build trigger on Cloud Console.

steps:
- name: gcr.io/k8s-skaffold/skaffold:v0.16.0
  args: ['skaffold', 'run', '-f=skaffold.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=demo-app-staging'
timeout: 1800s
options: # Add more power, and more time, for heavy Skaffold build
  machineType: 'N1_HIGHCPU_8'
