# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: skaffold/v1alpha4
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: gcr.io/loodse-workshop-11500/emailservice
    context: src/emailservice
  - image: gcr.io/loodse-workshop-11500/productcatalogservice
    context: src/productcatalogservice
  - image: gcr.io/loodse-workshop-11500/recommendationservice
    context: src/recommendationservice
  - image: gcr.io/loodse-workshop-11500/shippingservice
    context: src/shippingservice
  - image: gcr.io/loodse-workshop-11500/checkoutservice
    context: src/checkoutservice
  - image: gcr.io/loodse-workshop-11500/paymentservice
    context: src/paymentservice
  - image: gcr.io/loodse-workshop-11500/currencyservice
    context: src/currencyservice
  - image: gcr.io/loodse-workshop-11500/cartservice
    context: src/cartservice
  - image: gcr.io/loodse-workshop-11500/frontend
    context: src/frontend
#  - image: gcr.io/loodse-workshop-11500/loadgenerator
#    context: src/loadgenerator
  - image: gcr.io/loodse-workshop-11500/adservice
    context: src/adservice
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/app/**.yaml
profiles:
# "travis-ci" profile is used to build the images withou
# pushing them.
- name: travis-ci
  build:
    local:
      push: false
# "gcb" profile allows building and pushing the images
# on Google Container Builder without requiring docker
# installed on the developer machine. However, note that
# since GCB does not cache the builds, each build will
# start from scratch and therefore take a long time.
#
# This is not used by default. To use it, run:
#     skaffold run -p gcb
- name: gcb
  build:
    googleCloudBuild:
      projectId: loodse-workshop-11500
      diskSizeGb: 300
      machineType: N1_HIGHCPU_32
      timeout: 4000s

### load test profile, run with:
###    skaffold run --profile=loadtest
- name: loadtest
  build:
    artifacts:
    - image: gcr.io/loodse-workshop-11500/loadgenerator
      context: src/loadgenerator
  deploy:
    kubectl:
      manifests:
      - ./kubernetes-manifests/test/**.yaml
